apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: voting-app
spec:
  replicas: 1
  selector:
    app: voting-app
  template:
    metadata:
      labels:
        app: voting-app
    spec:
      containers:
        - name: voting-app
          image: "voting-app:latest"
          ports:
            - containerPort: 8080
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - voting-app
        from:
          kind: ImageStreamTag
          name: 'voting-app:latest'
